default filter:

  uses default for null, false, and empty strings or nonscalars:
  - '{{ "foo" | default: "bar" }}': foo
  - '{{ null | default: "bar" }}': bar
  - '{{ "" | default: "bar" }}':  bar
  - '{{ false | default: "bar" }}': bar
  - TPL: '{{ foo0 | default: "bar" }}'
    EXP: bar
    CTX: { foo0: [] }
  - TPL: '{{ foo0 | default: "bar" }}'
    EXP: bar
    CTX: { foo0: {} }
  - TPL: "{{ drop | default: 'bar' }}"
    EXP: Yay
    CTX: { drop: !ruby/object:BooleanDrop { value: true } }
  - "{{ false | default: 'bar' }}": bar
  - TPL: "{{ drop | default: 'bar' }}"
    EXP: bar
    CTX: { drop: !ruby/object:BooleanDrop { value: false } }


  with allow_false:
    flips the behaviour for false only:
    - '{{ "foo" | default: "bar", allow_false: true }}': foo
    - '{{ null | default: "bar", allow_false: true }}': bar
    - '{{ "" | default: "bar", allow_false: true }}': bar
    - '{{ false | default: "bar", allow_false: true }}': 'false'
    - TPL: '{{ foo0 | default: "bar", allow_false: true }}'
      EXP: bar
      CTX: { foo0: [] }
    - TPL: '{{ foo0 | default: "bar", allow_false: true }}'
      EXP: bar
      CTX: { foo0: {} }
    - "{{ false | default: 'bar', allow_false: true }}": 'false'
    - TPL: "{{ drop | default: 'bar', allow_false: true }}"
      EXP: Nay
      CTX: { drop: !ruby/object:BooleanDrop { value: false } }
    - TPL: "{{ drop | default: 'bar', allow_false: true }}"
      EXP: Yay
      CTX: { drop: !ruby/object:BooleanDrop { value: true } }


